### ISSUE TITLE
报错  Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

### ISSUE THREAD

**Issue by wangzongming** [LovesAsuna/SimpleBot#3]
![image](https://user-images.githubusercontent.com/27466569/97182408-75ff3880-17d7-11eb-8013-000e0f9a9d73.png)

啥子问题额？

**Comment by LovesAsuna** [comment]
?写的明明白白，异地登陆。在这台设备上先挂qq挂个几天就能用了

**Comment by wangzongming** [comment]
误会，误会。换了个qq我密码输入错了还是提示这个，还以为哪出问题了。感谢
